#!/usr/bin/env bash
# Regenerates THIRD-PARTY-NOTICES.md from the licence texts actually present
# in the configured build tree.
#
# Generated rather than hand-written on purpose: raylib vendors a dozen
# libraries and that set changes between releases, so a hand-maintained notice
# file goes stale silently. Run this after bumping any dependency pin.
#
#   tools/gen_third_party_notices.sh [build-dir]      # default: build/debug
set -euo pipefail

build_dir="${1:-build/debug}"
deps="${build_dir}/_deps"
out="THIRD-PARTY-NOTICES.md"

if [[ ! -d "${deps}" ]]; then
    echo "error: ${deps} not found -- configure a build first:" >&2
    echo "  cmake -S . -B ${build_dir} -DCMAKE_BUILD_TYPE=Debug" >&2
    exit 1
fi

# Emits a section with a licence file quoted verbatim.
emit() {
    local name="$1" role="$2" path="$3"
    if [[ ! -f "${path}" ]]; then
        echo "warning: no licence file for ${name} at ${path}" >&2
        return
    fi
    {
        printf '\n## %s\n\n%s\n\n```\n' "${name}" "${role}"
        cat "${path}"
        printf '```\n'
    } >> "${out}"
}

# Extracts the licence header from a single-file library that has no separate
# licence file (the stb-style headers keep it in a trailing comment block).
emit_header_licence() {
    local name="$1" role="$2" path="$3"
    if [[ ! -f "${path}" ]]; then
        echo "warning: ${name} not found at ${path}" >&2
        return
    fi
    {
        printf '\n## %s\n\n%s\n\n```\n' "${name}" "${role}"
        # The licence is stated in the first 40 lines of every one of these.
        head -40 "${path}" | grep -iE 'copyright|licen|public domain|SPDX|permission' || true
        printf '```\n'
    } >> "${out}"
}

cat > "${out}" <<'HEADER'
# Third-party notices

This project links the following third-party software. Every licence below is
permissive; none is copyleft. Where a licence requires it (MIT and similar),
this file constitutes the required attribution for binary distribution.

**Generated by `tools/gen_third_party_notices.sh` — do not edit by hand.**
Re-run it after changing any dependency version.
HEADER

emit "raylib" "Windowing, rendering, input and audio. Statically linked." \
    "${deps}/raylib-src/LICENSE"
emit "flecs" "Entity Component System. Statically linked." \
    "${deps}/flecs-src/LICENSE"

ext="${deps}/raylib-src/src/external"
emit "GLFW" "Vendored by raylib for window and input handling." \
    "${ext}/glfw/LICENSE.md"

# Single-header libraries vendored inside raylib and compiled into the binary.
emit_header_licence "cgltf" "Vendored by raylib: glTF model loading." \
    "${ext}/cgltf.h"
emit_header_licence "miniaudio" "Vendored by raylib: audio device and mixing." \
    "${ext}/miniaudio.h"
emit_header_licence "stb_image" "Vendored by raylib: image decoding." \
    "${ext}/stb_image.h"
emit_header_licence "stb_truetype" "Vendored by raylib: font rasterisation." \
    "${ext}/stb_truetype.h"
emit_header_licence "dr_wav" "Vendored by raylib: WAV decoding." \
    "${ext}/dr_wav.h"
emit_header_licence "dr_mp3" "Vendored by raylib: MP3 decoding." \
    "${ext}/dr_mp3.h"
emit_header_licence "qoa" "Vendored by raylib: QOA audio decoding." \
    "${ext}/qoa.h"
emit_header_licence "qoi" "Vendored by raylib: QOI image decoding." \
    "${ext}/qoi.h"
emit_header_licence "par_shapes" "Vendored by raylib: parametric mesh generation." \
    "${ext}/par_shapes.h"
emit_header_licence "m3d" "Vendored by raylib: M3D model loading." \
    "${ext}/m3d.h"

cat >> "${out}" <<'FOOTER'

## Deliberately excluded

`jar_xm` and `jar_mod` (XM/MOD tracker music, WTFPL) ship with raylib but are
compiled out via `SUPPORT_FILEFORMAT_XM=0` / `SUPPORT_FILEFORMAT_MOD=0` in
`cmake/MyeDependencies.cmake`. Verify with:

    nm build/debug/_deps/raylib-build/raylib/libraylib.a | grep -ci 'jar_xm\|jar_mod'

which must print 0.
FOOTER

echo "wrote ${out}"
